# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: bemo
email: blog@bemo.life
description: > # this means to ignore newlines until "baseurl:"
  Get help for your anxiety instantly ​with hand-picked therapists & analytics driven therapy.
  
  
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rish0957.github.io/bemo/" # the base hostname & protocol for your site

#sidebar
default-image: bemo_logo.png # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: bemo
copyright:
   name: bemo
   link: 'http://bemo.life'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Comments
disqus-shortname: blog-bemo

#social
facebook: https://www.facebook.com/lifewithbemo
quora: https://twitter.com/lifewithbemo
twitter: https://twitter.com/lifewithbemo
github: https://twitter.com/lifewithbemo

#facebook like box
fb-app-id: 158595664698619
fb-page-url: https://www.facebook.com/lifewithbemo/
fb-page-title: Bemo

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins: [jekyll-paginate, jekyll-seo-tag]

